import { redirect } from 'next/navigation';
import styles from '../ui.module.css';
import { readState, updateStateLocked, getPublicBaseUrl, addAuditEvent } from '@/lib/store';
import { clearSession, getSession } from '@/lib/session';
import { randomToken, sha256Hex } from '@/lib/crypto';
import { sendInviteEmail } from '@/lib/email';
import { getRequestOrigin } from '@/lib/request';

export const dynamic = 'force-dynamic';

export default async function AdminPage() {
  const state = readState();
  if (!state.setup?.complete) redirect('/setup');

  const session = await getSession();
  if (!session) {
    return (
      <div className={styles.container}>
        <h1 className={styles.h1}>Login required</h1>
        <p className={styles.p}>Please log in as an admin to continue.</p>
        <p className={styles.p}>
          <a className={styles.a} href="/login">Go to login</a>
        </p>
      </div>
    );
  }

  if (session.role !== 'admin') {
    return (
      <div className={styles.container}>
        <h1 className={styles.h1}>Admin only</h1>
        <p className={styles.p}>You’re logged in, but this page requires admin access.</p>
        <p className={styles.p}>
          <a className={styles.a} href="/signup">Go to signup</a>
        </p>
      </div>
    );
  }

  const signups = Array.isArray(state.signups) ? state.signups.slice().reverse() : [];
  const servers = Array.isArray(state.servers) ? state.servers : [];

  async function deleteSignupAction(formData) {
    'use server';

    const session2 = await getSession();
    if (!session2 || session2.role !== 'admin') throw new Error('Unauthorized.');

    const id = String(formData.get('id') || '').trim();
    if (!id) throw new Error('Missing id.');

    await updateStateLocked((s) => {
      s.signups = Array.isArray(s.signups) ? s.signups : [];
      s.signups = s.signups.filter((x) => String(x?.id || '') !== id);
      addAuditEvent(s, {
        type: 'admin_signup_deleted',
        actor: 'admin',
        message: 'Signup deleted by admin.',
        meta: { signupId: id },
      });
      return s;
    });

    redirect('/admin');
  }

  async function expireInviteAction(formData) {
    'use server';

    const session2 = await getSession();
    if (!session2 || session2.role !== 'admin') throw new Error('Unauthorized.');

    const id = String(formData.get('id') || '').trim();
    if (!id) throw new Error('Missing id.');

    await updateStateLocked((s) => {
      const signup = (s.signups || []).find((x) => String(x?.id || '') === id);
      if (!signup) throw new Error('Signup not found.');
      signup.tokenExpiresAt = Date.now() - 1000;
      signup.status = 'expired';
      signup.error = '';

      addAuditEvent(s, {
        type: 'admin_invite_expired',
        actor: 'admin',
        message: 'Invite expired by admin.',
        meta: { signupId: id },
      });
      return s;
    });

    redirect('/admin');
  }

  async function resendInviteAction(formData) {
    'use server';

    const session2 = await getSession();
    if (!session2 || session2.role !== 'admin') throw new Error('Unauthorized.');

    const id = String(formData.get('id') || '').trim();
    if (!id) throw new Error('Missing id.');

    const snapshot = readState();
    const existing = (snapshot.signups || []).find((x) => String(x?.id || '') === id);
    if (!existing) throw new Error('Signup not found.');
    if (existing.status === 'provisioned') throw new Error('User is already provisioned.');

    const token = randomToken(24);
    const tokenHash = sha256Hex(token);
    const origin = await getRequestOrigin();
    const statePublic = String(snapshot.publicBaseUrl || '').trim().replace(/\/+$/, '');
    const baseUrl = statePublic || getPublicBaseUrl() || origin;
    if (!baseUrl) throw new Error('Base URL is not configured. Set OPENSTREAM_PUBLIC_BASE_URL.');

    const inviteUrl = `${baseUrl}/set-password?token=${encodeURIComponent(token)}`;

    await updateStateLocked((s) => {
      const signup = (s.signups || []).find((x) => String(x?.id || '') === id);
      if (!signup) throw new Error('Signup not found.');
      signup.status = 'pending_email';
      signup.error = '';
      signup.tokenHash = tokenHash;
      signup.tokenExpiresAt = Date.now() + 24 * 60 * 60 * 1000;
      signup.tokenUsedAt = null;
      signup.passwordSetAt = null;
      signup.provisioningStartedAt = 0;

      addAuditEvent(s, {
        type: 'admin_invite_regenerated',
        actor: 'admin',
        message: 'Invite regenerated by admin.',
        meta: { signupId: id },
      });
      return s;
    });

    try {
      await sendInviteEmail({ to: String(existing.email || ''), inviteUrl });
      await updateStateLocked((s) => {
        const signup = (s.signups || []).find((x) => String(x?.id || '') === id);
        if (signup) {
          signup.status = 'invite_sent';
          signup.error = '';
        }
        addAuditEvent(s, {
          type: 'admin_invite_resent',
          actor: 'admin',
          message: 'Invite resent by admin.',
          meta: { signupId: id },
        });
        return s;
      });
    } catch (e) {
      await updateStateLocked((s) => {
        const signup = (s.signups || []).find((x) => String(x?.id || '') === id);
        if (signup) {
          signup.status = 'email_failed';
          signup.error = String(e?.message || e);
        }
        addAuditEvent(s, {
          type: 'admin_invite_resend_failed',
          actor: 'admin',
          message: 'Invite resend failed.',
          meta: { signupId: id, error: String(e?.message || e).slice(0, 500) },
        });
        return s;
      });
      throw e;
    }

    redirect('/admin');
  }

  function libraryNamesForSignup(signup) {
    const server = signup?.serverId ? servers.find((s) => s.id === signup.serverId) : null;
    const libraries = Array.isArray(server?.libraries) ? server.libraries : [];
    const nameById = new Map(libraries.map((l) => [String(l.id), String(l.name)]));

    const requested = Array.isArray(signup?.requestedLibraryIds) ? signup.requestedLibraryIds : null;
    if (!requested || requested.length === 0) return '';

    const names = requested.map((id) => nameById.get(String(id)) || String(id));
    return names.filter(Boolean).join(', ');
  }

  function statusInfo(status) {
    const s = String(status || '').trim();
    if (s === 'provisioned') return { label: 'Provisioned', className: `${styles.pill} ${styles.pillGood}` };
    if (s === 'provision_failed') return { label: 'Provision failed', className: `${styles.pill} ${styles.pillBad}` };
    if (s === 'email_failed') return { label: 'Email failed', className: `${styles.pill} ${styles.pillBad}` };
    if (s === 'provisioning') return { label: 'Provisioning', className: styles.pill };
    if (s === 'invite_sent') return { label: 'Invite sent', className: styles.pill };
    if (s === 'pending_email') return { label: 'Pending email', className: styles.pill };
    if (s === 'expired') return { label: 'Expired', className: styles.pill };
    return { label: s || '—', className: styles.pill };
  }

  function renderErrorCell(error) {
    const msg = String(error || '').trim();
    if (!msg) return '';
    if (msg.length <= 90) return msg;
    const preview = `${msg.slice(0, 90)}…`;
    return (
      <details>
        <summary className={styles.detailsSummary}>{preview}</summary>
        <div className={`${styles.detailsBody} ${styles.preWrap}`}>{msg}</div>
      </details>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.row}>
        <h1 className={styles.h1}>Admin</h1>
        <div className={styles.row}>
          <a className={styles.a} href="/admin/settings">Settings</a>
          <form action={async () => {
            'use server';
            await clearSession();
            redirect('/login');
          }}>
            <button className={styles.linkButton} type="submit">Logout</button>
          </form>
        </div>
      </div>

      <h2 className={styles.h2}>Signups</h2>
      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>When</th>
              <th>Server</th>
              <th>Libraries</th>
              <th>Username</th>
              <th>Email</th>
              <th>Status</th>
              <th>Error</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {signups.length === 0 ? (
              <tr><td colSpan={8}>No signups yet.</td></tr>
            ) : signups.map((s) => (
              <tr key={s.id}>
                <td>{new Date(s.createdAt).toLocaleString()}</td>
                <td>{s.serverName || s.serverType}</td>
                <td>{libraryNamesForSignup(s) || '—'}</td>
                <td>{s.username}</td>
                <td>{s.email}</td>
                <td>
                  {(() => {
                    const info = statusInfo(s.status);
                    return <span className={info.className}>{info.label}</span>;
                  })()}
                </td>
                <td>{renderErrorCell(s.error)}</td>
                <td>
                  <div className={styles.actions}>
                    {s.status !== 'provisioned' ? (
                      <form action={resendInviteAction}>
                        <input type="hidden" name="id" value={s.id} />
                        <button className={styles.smallButton} type="submit">Resend invite</button>
                      </form>
                    ) : null}

                    {s.status !== 'provisioned' && s.status !== 'expired' && Number(s.tokenExpiresAt || 0) > Date.now() ? (
                      <form action={expireInviteAction}>
                        <input type="hidden" name="id" value={s.id} />
                        <button className={styles.smallButton} type="submit">Expire</button>
                      </form>
                    ) : null}

                    <form action={deleteSignupAction}>
                      <input type="hidden" name="id" value={s.id} />
                      <button className={styles.smallButton} type="submit">Delete</button>
                    </form>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
